# 1)	Define the following metrics and perform the following operations

    i) Write a Python program using Python Lists
    ii) Write a Python program and NumPy
    
    

```python
Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].
```


<b>Using Python Lists</b> 

In [1]:
A = [[3.7827, 3.3454, 3.2341], 
     [2.2122, 3.5678, 3.9087], 
     [1.1234, 2.8934, 5.9087]]

B = [[3.1234, 3.0987, 3.1234], 
     [2.1111, 3.2222, 3.3333], 
     [1.0987, 1.3456, 5.1234]]

C = [[3.1243, 3.0989, 3.1256], 
     [2.6721, 3.6785, 3.9017], 
     [1.1254, 2.8956, 5.9187]]


print("Matrix A")
print(A)
print("\nMatrix B")
print(B)
print("\nMatrix C")
print(C)

Matrix A
[[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]

Matrix B
[[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]

Matrix C
[[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]


<b>Using NumPy</b> 

In [2]:
import numpy as np


A = np.array([[3.7827, 3.3454, 3.2341], 
              [2.2122, 3.5678, 3.9087], 
              [1.1234, 2.8934, 5.9087]])

B = np.array([[3.1234, 3.0987, 3.1234], 
              [2.1111, 3.2222, 3.3333], 
              [1.0987, 1.3456, 5.1234]])

C = np.array([[3.1243, 3.0989, 3.1256], 
              [2.6721, 3.6785, 3.9017], 
              [1.1254, 2.8956, 5.9187]])


print("Matrix A")
print(A)
print("\nMatrix B")
print(B)
print("\nMatrix C")
print(C)

Matrix A
[[3.7827 3.3454 3.2341]
 [2.2122 3.5678 3.9087]
 [1.1234 2.8934 5.9087]]

Matrix B
[[3.1234 3.0987 3.1234]
 [2.1111 3.2222 3.3333]
 [1.0987 1.3456 5.1234]]

Matrix C
[[3.1243 3.0989 3.1256]
 [2.6721 3.6785 3.9017]
 [1.1254 2.8956 5.9187]]


# 2)	Write a Python Program and perform the following operations

I.    Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}

In [3]:
numberList = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]\

print(numberList)

[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


II.    Iterate using a for loop

In [4]:
for number in numberList:
    print(number)

1225
4986
6789
7890
2345
6783
987
1234
8765
3456


III.    Iterate using for loop and range

In [5]:
for i in range(len(numberList)):
    print(numberList[i])

1225
4986
6789
7890
2345
6783
987
1234
8765
3456


IV.    List Comprehension

In [6]:
new_list = [number for number in numberList]

print(new_list)

[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]


V.    Enumerate

In [7]:
for index, number in enumerate(numberList):
    print(index, number)

0 1225
1 4986
2 6789
3 7890
4 2345
5 6783
6 987
7 1234
8 8765
9 3456


VI.    Iter function and next function

In [8]:
iterator = iter(numberList)

while True:
    try:
        number = next(iterator)
        print(number)
    except StopIteration:
        break

1225
4986
6789
7890
2345
6783
987
1234
8765
3456


VII.    Map function

In [9]:
def square(number):
    return number ** 2

squared_numbers = map(square, numberList)

print(list(squared_numbers))

[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]


VIII.    Using zip

In [10]:
numberList1 = [1, 2, 3, 4, 5]
numberList2 = [10, 20, 30, 40, 50]

for num1, num2 in zip(numberList1, numberList2):
    print(num1, num2)

1 10
2 20
3 30
4 40
5 50


IX.    Using NumPy Module

In [11]:
import numpy as np

numberArray = np.array(numberList)

print(numberArray)

[1225 4986 6789 7890 2345 6783  987 1234 8765 3456]


# 3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [12]:
def combinations(lst):
  if not lst:
    return [[]]
  return [[lst[0]] + comb for comb in combinations(lst[1:])] + combinations(lst[1:])

def permutations(lst):
  if len(lst) <= 1:
    return [lst]
  perms = []
  for i in range(len(lst)):
    perms.extend([[lst[i]] + p for p in permutations(lst[:i] + lst[i+1:])])
  return perms

list = ["A", "B", "C", "D", "E"]

print("Combinations\n")
for combination in combinations(list):
    print(combination)

print("\n\n")
print("Permutations\n")
for permutation in permutations(list):
    print(permutation)

Combinations

['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'D']
['A', 'B', 'C', 'E']
['A', 'B', 'C']
['A', 'B', 'D', 'E']
['A', 'B', 'D']
['A', 'B', 'E']
['A', 'B']
['A', 'C', 'D', 'E']
['A', 'C', 'D']
['A', 'C', 'E']
['A', 'C']
['A', 'D', 'E']
['A', 'D']
['A', 'E']
['A']
['B', 'C', 'D', 'E']
['B', 'C', 'D']
['B', 'C', 'E']
['B', 'C']
['B', 'D', 'E']
['B', 'D']
['B', 'E']
['B']
['C', 'D', 'E']
['C', 'D']
['C', 'E']
['C']
['D', 'E']
['D']
['E']
[]



Permutations

['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'E', 'D']
['A', 'B', 'D', 'C', 'E']
['A', 'B', 'D', 'E', 'C']
['A', 'B', 'E', 'C', 'D']
['A', 'B', 'E', 'D', 'C']
['A', 'C', 'B', 'D', 'E']
['A', 'C', 'B', 'E', 'D']
['A', 'C', 'D', 'B', 'E']
['A', 'C', 'D', 'E', 'B']
['A', 'C', 'E', 'B', 'D']
['A', 'C', 'E', 'D', 'B']
['A', 'D', 'B', 'C', 'E']
['A', 'D', 'B', 'E', 'C']
['A', 'D', 'C', 'B', 'E']
['A', 'D', 'C', 'E', 'B']
['A', 'D', 'E', 'B', 'C']
['A', 'D', 'E', 'C', 'B']
['A', 'E', 'B', 'C', 'D']
['A', 'E', 'B', 'D', 'C']
['A', 'E', 'C',

# 4)	Using the same list use itertools compute permutations and combinations 

In [13]:
import itertools

def combinations(elements):
    combinations = []

    for length in range(1, len(elements) + 1):
        combinations.extend(itertools.combinations(elements, length))

    return combinations

def permutations(elements):
    permutations = []

    for length in range(1, len(elements) + 1):
        permutations.extend(itertools.permutations(elements, length))

    return permutations


list = ["A", "B", "C", "D", "E"]

print("Combinations\n")
for combination in combinations(list):
    print(combination)

print("\n\n")
print("Permutations\n")
for permutation in permutations(list):
    print(permutation)

Combinations

('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'D')
('C', 'E')
('D', 'E')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'E')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'E')
('C', 'D', 'E')
('A', 'B', 'C', 'D')
('A', 'B', 'C', 'E')
('A', 'B', 'D', 'E')
('A', 'C', 'D', 'E')
('B', 'C', 'D', 'E')
('A', 'B', 'C', 'D', 'E')



Permutations

('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'A')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'A')
('C', 'B')
('C', 'D')
('C', 'E')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'E')
('E', 'A')
('E', 'B')
('E', 'C')
('E', 'D')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'B')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'B')
('A', 'D', 'C')
('A', 'D', 'E')
('A', 'E', 'B')
('A', 'E', 'C')
('A', 'E', 'D')
('B', 'A', 'C')
('B', 'A', 'D')
('B', 'A', 'E')
('B', 'C', 'A')
('B', 'C', 'D')
('B', 